<?php

/**
 * Implements hook_preprocess_link().
 */
function link_trail_by_path_preprocess_link(&$link) {
  module_load_include('inc', 'link_trail_by_path', 'link_trail_by_path.helpers');

  $link_parent_candidates = _link_trail_by_path_get_parent_candidates($link['path']);
  $current_path_parent_candidates = _link_trail_by_path_get_parent_candidates(drupal_get_path_alias());

  if (empty($link_parent_candidates) || empty($current_path_parent_candidates)) {
    return;
  }

  if (in_array(end($link_parent_candidates), $current_path_parent_candidates)) {
    if (isset($link['options']['attributes']['class'])) {
      if (is_array($link['options']['attributes']['class'])) {
        $link['options']['attributes']['class'][] = 'active-trail';
      } else {
        $link['options']['attributes']['class'] .= ' active-trail';
      }
    } else {
      $link['options']['attributes'] += array('class' => array('active-trail'));
    }
  }
}
